/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
    './utils/**/*.{ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Legacy brand tokens
        brand: {
          deepBlue: '#0A1F3D',
          cyan: '#3DB4F2',
          offWhite: '#F5F7FA',
          mint: '#34D399',
          amber: '#F59E0B',
        },
        // Material 3 design system tokens
        primary: '#b4c7ed',
        'on-primary': '#1e304f',
        'primary-container': '#0a1f3d',
        'on-primary-container': '#7587ab',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#b4c7ed',
        'on-primary-fixed': '#061b39',
        'on-primary-fixed-variant': '#354767',
        'inverse-primary': '#4d5f80',
        secondary: '#84cfff',
        'on-secondary': '#00344c',
        'secondary-container': '#009ad7',
        'on-secondary-container': '#002d42',
        'secondary-fixed': '#c7e7ff',
        'secondary-fixed-dim': '#84cfff',
        'on-secondary-fixed': '#001e2e',
        'on-secondary-fixed-variant': '#004c6c',
        tertiary: '#45dfa4',
        'on-tertiary': '#003825',
        'tertiary-container': '#002517',
        'on-tertiary-container': '#009a6c',
        'tertiary-fixed': '#68fcbf',
        'tertiary-fixed-dim': '#45dfa4',
        'on-tertiary-fixed': '#002114',
        'on-tertiary-fixed-variant': '#005137',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#131316',
        'on-background': '#e4e2e5',
        surface: '#131316',
        'on-surface': '#e4e2e5',
        'surface-variant': '#343537',
        'on-surface-variant': '#c5c6ce',
        'surface-dim': '#131316',
        'surface-bright': '#39393c',
        'surface-container-lowest': '#0d0e10',
        'surface-container-low': '#1b1b1e',
        'surface-container': '#1f1f22',
        'surface-container-high': '#292a2c',
        'surface-container-highest': '#343537',
        'inverse-surface': '#e4e2e5',
        'inverse-on-surface': '#303033',
        outline: '#8e9098',
        'outline-variant': '#44474e',
        'surface-tint': '#b4c7ed',
      },
      fontFamily: {
        sans: ['System'],
        'space-grotesk': ['SpaceGrotesk_700Bold'],
      },
    },
  },
  plugins: [],
};
